### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by andyz245** [ltzheng/Synapse#1]
Hi,
Thanks for the contribution! I tried running your repo but ran into this error after installing the packages.

RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open exemplar_lib/index.faiss for reading: No such file or directory

**Comment by ltzheng** [comment]
It is necessary to add the "--init_db" argument to initialize the exemplar database for the first run.
