### ISSUE TITLE
How to evaluate the output on Mind2Web dataset?

### ISSUE THREAD

**Issue by TheVishT** [ltzheng/Synapse#10]
I followed the setup instructions in the README file: I set up the Mind2Web data directory and ran build_memory.py and run_mind2web.py with the test_website benchmark from the Mind2Web dataset. This process generated output in a folder named "result," containing 177 .json files.

Here are the points I need help with:

1. Number of Output Files: Although test_website has only 2 .json files, I ended up with 177 output files. I assume that the 2 input .json files collectively contain 177 inputs, but I’m not entirely sure if that's correct.

2. Message: "Ground Truth Element Not in Cleaned HTML": In some output files, I see this message. I’m not sure what it means.

3. Calculating Performance Metrics: I’m unsure how to generate the overall performance metrics (such as element accuracy, step success rate, success rate, etc.) as described in the research paper. I think I need to aggregate results from the output files, but I’m not clear on how to do it.

Could you help clarify these points?

**Comment by ltzheng** [comment]
1. Yes. I guess you are running Mind2Web Cross-Website, which has 177 instances.
2. We use the cleaned HTML from Mind2Web. This message indicates that the cleaned HTML does not contain the target element. You can refer to [here](https://github.com/ltzheng/Synapse/blob/af355d29a87177a457957a17ac993366152888ad/synapse/agents/mind2web.py#L104).
3. The metrics are initialized [here](https://github.com/ltzheng/Synapse/blob/main/synapse/agents/mind2web.py#L30). You can also aggregate results from the output files according to the way we update the metrics in this code.

**Comment by TheVishT** [comment]
Thanks for the quick reply! The first two points are clear now.

For the third point, I did see metrics in the output files, but my main question is about how to aggregate these to get the overall performance of the model on this benchmark. Should I just take the average over all actions within a single instance and then average across all instances, or is there a different approach I should use?

**Comment by ltzheng** [comment]
Averaging twice in this way could introduce errors. A more reasonable approach would be to aggregate the results from all instances first and then calculate a single average.

**Comment by TheVishT** [comment]
It worked. My doubt has been cleared. Thank you for your help.
