### ISSUE TITLE
Running finetune_mind2web.py

### ISSUE THREAD

**Issue by TheVishT** [ltzheng/Synapse#11]
In this command:
python finetune_mind2web.py --data_dir path/to/Mind2Web/data --base_model codellama/CodeLlama-7b-Instruct-hf --cache_dir <MODEL_PATH> --lora_dir <CHECKPOINT_PATH> --top_k_elements 20
I am not able to understand what path should be given for MODEL_PATH and CHECKPOINT_PATH. 

Also, for the finetuning part, in the README file, there were only two options:
1. python finetune_mind2web.py --data_dir path/to/Mind2Web/data --base_model codellama/CodeLlama-7b-Instruct-hf --cache_dir <MODEL_PATH> --lora_dir <CHECKPOINT_PATH> --no_trajectory --top_k_elements 20
2. python finetune_mind2web.py --data_dir path/to/Mind2Web/data --base_model codellama/CodeLlama-7b-Instruct-hf --cache_dir <MODEL_PATH> --lora_dir <CHECKPOINT_PATH> --top_k_elements 20
Is there any reason for not using the -no_memory option?.

**Comment by ltzheng** [comment]
MODEL_PATH is the path (or model name) of the base language model. CHECKPOINT_PATH is the path for the lora module.

In finetuning, we didn't try using memory to construct few-shot prompts because of the context limit of the base model and those few-shot examples are also in the training data.

**Comment by TheVishT** [comment]
Thanks for the quick reply. It would be very helpful if you could guide me on where to find the Lora module and the base language model.

**Comment by ltzheng** [comment]
In the finetuning code, the --lora_dir is just the location to save the trained lora. If you download the LM locally, use --cache_dir to specify the location. Otherwise, it will download automatically into huggingface cache folder.

**Comment by TheVishT** [comment]
Thanks, I understand now!

I'm looking to simulate the output of the model as actions on a website and wondered if you've done something similar before. I've looked into frameworks that could support this but haven't found anything suitable. Do you have any suggestions on how to approach this?

**Comment by ltzheng** [comment]
I think the [Claude computer use demo](https://docs.anthropic.com/en/docs/build-with-claude/computer-use) may be helpful.
