### ISSUE TITLE
fine-tuning performance

### ISSUE THREAD

**Issue by gdg94** [ltzheng/Synapse#12]
Hi, thanks for the super interesting work!
I'm hoping to ask about what the fine-tuning script is used for? (Is it fine-tuning the agent or a small model for compressing the HTML?
And for training and evaluation of the main Synapse model, is fine-tuning a required step?
Thank you very much :)

**Comment by ltzheng** [comment]
The finetuning script is for finetuning codellama using Synapse-like data template.
The original Synapse is an in-context learning, which does not involve finetuning. Therefore, you don't have to do finetuning to use Synapse.

**Comment by gdg94** [comment]
Awesome! Thank you very much!
