### ISSUE TITLE
chromadb missing from requirements.txt

### ISSUE THREAD

**Issue by maccam912** [ltzheng/Synapse#2]
I had to add "chromadb<0.4" for the book flight example to make it past an import issue, and then a chromadb version issue. Perhaps it belongs in requirements.txt?

**Comment by ltzheng** [comment]
We use Faiss instead of ChromaDB. Btw we have refactored the code recently. Please check it out.

**Comment by maccam912** [comment]
Thanks! I'm struggling a little right now getting the mind2web set up (FileNotFoundError: [Errno 2] No such file or directory: '.\\Mind2Web\\data\\train\\scores_all_data.pkl') but no longer related to chromadb, you can close this.
