### ISSUE TITLE
More guidance on getting scores_all_data.pkl file?

### ISSUE THREAD

**Issue by maccam912** [ltzheng/Synapse#3]
Thanks for updating this! I see the new structure, and I think I can get the train and test data as described, but I don't know where this scores_all_data.pkl file is coming from. Is that something that can be shared somewhere?

**Comment by ltzheng** [comment]
The scores_all_data.pkl contains the scores of all elements in Mind2Web HTML state. It can be downloaded from [their repository](https://github.com/OSU-NLP-Group/Mind2Web#candidate-generation).

**Comment by maccam912** [comment]
Ah perfect! That was just the push I needed to find it.
