### ISSUE TITLE
Does trajectories success?

### ISSUE THREAD

**Issue by njucckevin** [ltzheng/Synapse#4]
Hi, thanks for the nice work!

I downloaded the trajectories you provided in https://drive.google.com/file/d/1CnM3GF4kTAMZkGFasSXZ4Z2n5eiV8M9Z/view?usp=sharing. I found that some of the trajectory may lead to a -1.0 reward. However, the trajectory is marked as success in the filename.
For example, for enter-date task, the trajectory you provided looks like:
```
agent.click_xpath("//*[@id='tt']")
agent.press("arrowleft")
agent.press("arrowleft")
agent.type('10/11/2011')
agent.click_xpath("//*[@id='subbtn']")
```
However, these steps can not complete the task and result in a -1.0 reward.
Looking forward to your reply, thank!

**Comment by ltzheng** [comment]
Thanks. The date format in MiniWoB is related to the system setting. The exemplars here are using the US date format. I guess your operating system is not using `en_US.UTF-8` as date format.

**Comment by njucckevin** [comment]
That sounds reasonable. So do you know how to set the miniwob environment to the en_US.UTF-8? After clone the code of Synapse, what should I do?

**Comment by ltzheng** [comment]
Here is how to set the date format in Ubuntu.
1. Open a terminal.
2. Check current locale settings with the command: `locale`.
3. Update the system's locale settings:
    1. Open `/etc/default/locale` in an editor.
    2. Set `LANG` to `LANG="en_US.UTF-8"`.
    3. Set `LANGUAGE` to `LANGUAGE="en_US:en"`.
    4. Save and exit the editor.
4. Reboot for changes to take effect.
