### ISSUE TITLE
Stuck when executing the example instructions

### ISSUE THREAD

**Issue by jim850223** [ltzheng/Synapse#9]
Hello, 
thank you for the contribution, but I've bumped into the problem when I was following the instructions.

After executing 
python3 run_miniwob.py --env_name book-flight --seed 0 --num_episodes 50,
the prossess showed 
2024-10-22 14:07:52,607 - INFO - Retrieved exemplars: ['book-flight', 'book-flight', 'book-flight']
and stuck without moving on.
And when I executed 
python3 run_miniwob.py --env_name copy-paste-2 --no_memory --no_filter --seed 0 --num_episodes 3
It would just stuck without even showing anything.
I wonder how I can solve these problems, and look forward to your answer.

Thank you.

**Comment by ltzheng** [comment]
Can you locate where the code got stuck?

**Comment by jim850223** [comment]
For example, it will stuck there without proceeding any further, and the page of miniwob would not be controlled by the process(or seem to be not controlled since it would stuck in this page).
<img width="637" alt="image" src="https://github.com/user-attachments/assets/82e70f9f-6407-469b-8175-95e3834fad3c">

**Comment by ltzheng** [comment]
Can you step into the code and check which line of code is blocking? Otherwise we cannot reproduce your problem.

**Comment by jim850223** [comment]
I've solved it by myself, but thank you for answering.
